title: Emily Waterman # your name (or website title) here
logo: "images/ovalHeadshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Environmental Specialist with an expertise in geospatial analysis,
  which allows me to identify ecological conditions in places that would be impractical to study in situ. 
  I have a varied background of experience that includes serving in the Army, years of customer service,
  professional report writing, and scientific field data collection.  One of my lifelong passions has been
  to contribute to environmental sustainability, which I have done so through restoration efforts,
  environmental quality data collection, and land use identification.
  <br> <br>
  <a href="https://www.linkedin.com/in/emily-r-waterman/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
